//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVEUCILISNA_KNJIZNICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcija_Audit
    {
        public int TransakcijaID { get; set; }
        public string Status { get; set; }
    
        public virtual Transakcija Transakcija { get; set; }
        public virtual Transakcija_Audit Transakcija_Audit1 { get; set; }
        public virtual Transakcija_Audit Transakcija_Audit2 { get; set; }
    }
}
