//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVEUCILISNA_KNJIZNICA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transakcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transakcija()
        {
            this.BrojDokumentas = new HashSet<BrojDokumenta>();
        }
    
        public int TransakcijaID { get; set; }
        public System.DateTime DatumTransakcije { get; set; }

        [Display(Name = "Korisnik")]
        public int KorisnikID { get; set; }

        [Display(Name = "Knjiga")]
        public int KnjigaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrojDokumenta> BrojDokumentas { get; set; }
        public virtual Knjiga Knjiga { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Transakcija_Audit Transakcija_Audit { get; set; }
    }
}
